
project_id = "uzqxvwavuokaytrluqee"

[api]
enabled = true

[db]
enabled = true

[realtime]
enabled = true

[functions.send-guardian-email]
verify_jwt = false
[functions.send-guardian-email.secrets]
# RESEND_API_KEY = "RESEND_API_KEY" # Kept for reference if Resend is used later
MAILJET_PUB_KEY = "MAILJET_API_KEY" # Maps to the MAILJET_API_KEY secret you added
MAILJET_PRIV_KEY = "MAILJET_API_SECRET" # Maps to the MAILJET_API_SECRET secret you added
MAILJET_FROM_EMAIL = "MAILJET_SENDER_EMAIL" # Maps to the MAILJET_SENDER_EMAIL secret you will add

