
    // This file is automatically generated. Do not edit it directly.
    import { createClient } from '@supabase/supabase-js';
    import type { Database } from './types';

    // Ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in your Netlify environment variables
    const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

    if (!SUPABASE_URL) {
      console.error("Error: VITE_SUPABASE_URL is not defined. Please set it in your environment variables.");
      // You could throw an error here or provide a fallback, but for deployment, it must be set.
    }

    if (!SUPABASE_PUBLISHABLE_KEY) {
      console.error("Error: VITE_SUPABASE_ANON_KEY is not defined. Please set it in your environment variables.");
    }

    // Import the supabase client like this:
    // import { supabase } from "@/integrations/supabase/client";

    export const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!);
    