// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzqxvwavuokaytrluqee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6cXh2d2F2dW9rYXl0cmx1cWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDUzNjgsImV4cCI6MjA1ODk4MTM2OH0.a6EE98u5YM6D603draFqNb8abRDbYPGNXIegynO1mJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);